---
- name: ensure common packages are installed
  apt: name={{item}} state=present update_cache=yes
  become: yes
  with_items:
    - vim
    - zsh
    - git
    - tmux
    - screen
    - ack-grep
    - tree
    - ctags
