---
- name: check user.name for git is set
  shell: git config --global user.name
  register: result
  changed_when: false
  failed_when: false
- name: set user.name for git
  shell: git config --global user.name {{name}}
  when: result.stdout != name

- name: check user.email for git is set
  shell: git config --global user.email
  register: result
  changed_when: false
  failed_when: false
- name: set user.email for git
  shell: git config --global user.email {{email}}
  when: result.stdout != email
