---
- name: Set user.name for git
  git_config:
    name: user.name
    value: "{{name}}"
    scope: global

- name: Set user.email for git
  git_config:
    name: user.email
    value: "{{email}}"
    scope: global
