---
- name: Install packages for neovim
  apt:
    name: ['software-properties-common', # to use add-apt-repository
           'python-dev', 'python-pip', 'python3-dev', 'python3-pip']
    state: present
    update_cache: yes
  become: yes

- name: Add neovim ppa
  apt_repository:
    repo: ppa:neovim-ppa/stable
  become: yes

- name: Install neovim
  apt:
    name: neovim
    state: present
    update_cache: yes
  become: yes
