---
- name: fetch dotfiles from github
  git:  repo=git@github.com:{{github_account}}/dotfiles.git
          dest=~{{os_user}}/dotfiles accept_hostkey=true

- name: check .vimrc is up-to-date
  shell: diff ~{{os_user}}/dotfiles/.vimrc ~{{os_user}}/.vimrc
  register: result
  changed_when: false
  failed_when: false
- name: cp .vimrc
  shell: cp ~{{os_user}}/dotfiles/.vimrc ~{{os_user}}/.vimrc
  when: result.rc

- name: check .tmux.conf is up-to-date
  shell: diff ~{{os_user}}/dotfiles/.tmux.conf ~{{os_user}}/.tmux.conf
  register: result
  changed_when: false
  failed_when: false
- name: cp .tmux.conf
  shell: cp ~{{os_user}}/dotfiles/.tmux.conf ~{{os_user}}/.tmux.conf
  when: result.rc

- name: check .screenrc is up-to-date
  shell: diff ~{{os_user}}/dotfiles/.screenrc ~{{os_user}}/.screenrc
  register: result
  changed_when: false
  failed_when: false
- name: cp .screenrc
  shell: cp ~{{os_user}}/dotfiles/.screenrc ~{{os_user}}/.screenrc
  when: result.rc

- name: check .zshrc is up-to-date
  shell: diff ~{{os_user}}/dotfiles/.zshrc ~{{os_user}}/.zshrc
  register: result
  changed_when: false
  failed_when: false
- name: cp .zshrc
  shell: cp ~{{os_user}}/dotfiles/.zshrc ~{{os_user}}/.zshrc
  when: result.rc

- name: check .zshrc_prompt_color is up-to-date
  shell: diff ~{{os_user}}/dotfiles/.zshrc_prompt_color
    ~{{os_user}}/.zshrc_prompt_color
  register: result
  changed_when: false
  failed_when: false
- name: cp .zshrc_prompt_color
  shell: cp ~{{os_user}}/dotfiles/.zshrc_prompt_color
    ~{{os_user}}/.zshrc_prompt_color
  when: result.rc


- name: change login shell
  user: name={{os_user}} shell=/bin/zsh
  sudo: true
