---
- name: Fetch dotfiles from github
  git:
    repo: git@github.com:{{github_account}}/dotfiles.git
    dest: "{{ansible_env.HOME}}/dotfiles"
    accept_hostkey: true

## config files
- name: Copy .vimrc
  copy:
    src: "{{ansible_env.HOME}}/dotfiles/.vimrc"
    dest: "{{ansible_env.HOME}}/.vimrc"
    remote_src: yes

- name: Copy .tmux.conf
  copy:
    src: "{{ansible_env.HOME}}/dotfiles/.tmux.conf"
    dest: "{{ansible_env.HOME}}/.tmux.conf"
    remote_src: yes

- name: Copy .screenrc
  copy:
    src: "{{ansible_env.HOME}}/dotfiles/.screenrc"
    dest: "{{ansible_env.HOME}}/.screenrc"
    remote_src: yes


# NVIM
- name: Create ~/.config/nvim directory
  file:
    path: "{{ansible_env.HOME}}/.config/nvim"
    state: directory
- name: Copy .config/nvim/init.vim
  copy:
    src: "{{ansible_env.HOME}}/dotfiles/.config/nvim/init.vim"
    dest: "{{ansible_env.HOME}}/.config/nvim/init.vim"
    remote_src: yes

- name: Copy .dein.toml
  copy:
    src: "{{ansible_env.HOME}}/dotfiles/.dein.toml"
    dest: "{{ansible_env.HOME}}/.dein.toml"
    remote_src: yes

- name: Copy .dein_lazy.toml
  copy:
    src: "{{ansible_env.HOME}}/dotfiles/.dein_lazy.toml"
    dest: "{{ansible_env.HOME}}/.dein_lazy.toml"
    remote_src: yes


# dein
- name: Create ~/.cache/dein
  file:
    path: "{{ansible_env.HOME}}/.cache/dein"
    state: directory
- name: Install dein
  git:
    repo: https://github.com/Shougo/dein.vim
    dest: "{{ansible_env.HOME}}/.cache/dein/repos/github.com/Shougo/dein.vim"


# Zsh / Prezto
- name: Git clone prezto
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: "{{ansible_env.HOME}}/.zprezto"
- name: Link rcfiles
  file:
    src: "{{ansible_env.HOME}}/.zprezto/runcoms/{{item}}"
    dest: "{{ansible_env.HOME}}/.{{item}}"
    state: link
  loop: # zpreztorc and .zshrc are not symlinked because I have my own their files
    - zlogin
    - zlogout
    - zprofile
    - zshenv
- name: Copy .zshrc
  copy:
    src: "{{ansible_env.HOME}}/dotfiles/.zshrc"
    dest: "{{ansible_env.HOME}}/.zshrc"
    remote_src: yes
- name: Copy .zpreztorc
  copy:
    src: "{{ansible_env.HOME}}/dotfiles/.zpreztorc"
    dest: "{{ansible_env.HOME}}/.zpreztorc"
    remote_src: yes
- name: Make an external module directory
  file:
    path: "{{ansible_env.HOME}}/.zprezto-contrib"
    state: directory
- name: Git clone zsh-peco-history
  git:
    repo: https://github.com/jimeh/zsh-peco-history.git
    dest: "{{ansible_env.HOME}}/.zprezto-contrib/zsh-peco-history"


# etc
- name: Change login shell
  user: name={{os_user}} shell=/bin/zsh
  become: yes

- name: Create work directory
  file: path=~/work state=directory
