---
- name: ensure required packages are installed for Ruby
  apt: name={{item}} state=present
  sudo: true
  with_items:
    - git-core
    - curl
    - zlib1g-dev
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - software-properties-common

- name: add ruby-ng repository
  apt_repository: repo="ppa:brightbox/ruby-ng"
  sudo: true

- name: install ruby by apt
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - "{{ruby.package}}"
    - "{{ruby.package}}-dev"
  sudo: true

- name: check bundler gem is installed
  shell: gem list | grep bundler
  register: result
  changed_when: false
  failed_when: false

- name: install bundler gem
  shell: gem install bundler
  when: result.rc != 0
  sudo: true
