---
- name: Download and unarchive peco
  unarchive:
    src: https://github.com/peco/peco/releases/download/v0.5.2/peco_linux_amd64.tar.gz
    dest: /tmp
    remote_src: yes
- name: Install peco
  copy:
    remote_src: true
    src: /tmp/peco_linux_amd64/peco
    dest: /usr/local/bin/peco
    mode: 0755
  become: true
