---
- name: Install required apt packages for docker
  apt: name={{item}} state=present update_cache=yes
  become: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Install docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- shell: lsb_release -cs
  register: lsb_release
  changed_when: false

- name: Add apt repository for docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{lsb_release.stdout}} stable
  become: yes

- name: Install docker package
  apt: name=docker-ce state=present update_cache=yes
  become: yes

- name: Start docker
  systemd: name=docker state=started
  become: yes
