---
- name: install Ruby-related packages
  apt:
    name: ['git-core', 'curl', 'zlib1g-dev', 'build-essential', 'libssl-dev',
     'libreadline-dev', 'libyaml-dev', 'libsqlite3-dev', 'sqlite3',
     'libxml2-dev', 'libxslt1-dev', 'libcurl4-openssl-dev',
     'software-properties-common']
    state: present
  become: yes

- name: install system ruby by apt
  apt:
    name: ruby-full
    state: present
    update_cache: yes
  become: yes

- name: ensure rbenv is installed
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: "{{ansible_env.HOME}}/.rbenv"
- name: ensure ruby-build is installed
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: "{{ansible_env.HOME}}/.rbenv/plugins/ruby-build"
- name: ensure rbenv-binstubs is installed
  git:
    repo: https://github.com/ianheggie/rbenv-binstubs.git
    dest: "{{ansible_env.HOME}}/.rbenv/plugins/rbenv-binstubs"
- name: ensure rbenv-gemset is installed
  git:
    repo: https://github.com/jamis/rbenv-gemset.git
    dest: "{{ansible_env.HOME}}/.rbenv/plugins/rbenv-gemset"

- name: install bundle gem
  gem:
    name: bundler
    state: present
    user_install: no
  become: yes
