---
- name: ensure required packages are installed for Ruby
  apt: name={{item}} state=present
  sudo: true
  with_items:
    - git-core
    - curl
    - zlib1g-dev
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - software-properties-common

- name: add ruby-ng repository
  apt_repository: repo="ppa:brightbox/ruby-ng"
  sudo: true

- name: install system ruby by apt
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - "{{ruby.package}}"
    - "{{ruby.package}}-dev"
  sudo: true

- name: ensure rbenv is installed
  git:  repo=https://github.com/rbenv/rbenv.git
          dest=~{{os_user}}/.rbenv
- name: ensure ruby-build is installed
  git:  repo=https://github.com/rbenv/ruby-build.git
          dest=~{{os_user}}/.rbenv/plugins/ruby-build
- name: ensure rbenv-binstubs is installed
  git:  repo=https://github.com/ianheggie/rbenv-binstubs.git
          dest=~{{os_user}}/.rbenv/plugins/rbenv-binstubs
- name: ensure rbenv-gemset is installed
  git:  repo=https://github.com/jamis/rbenv-gemset.git
          dest=~{{os_user}}/.rbenv/plugins/rbenv-gemset

- name: check bundler gem is installed
  shell: gem list | grep bundler
  register: result
  changed_when: false
  failed_when: false

- name: install bundler gem
  shell: gem install bundler
  when: result.rc != 0
  sudo: true
